create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug = lower(slug)),
  excerpt text not null default '',
  content text not null default '',
  cover_url text,
  cover_alt text,
  seo_title text,
  seo_description text,
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.blog_posts enable row level security;
revoke all on table public.blog_posts from anon, authenticated;
grant select on table public.blog_posts to anon, authenticated;
grant all on table public.blog_posts to service_role;

drop policy if exists "Public can read published blog posts" on public.blog_posts;
create policy "Public can read published blog posts"
on public.blog_posts for select
to anon, authenticated
using (is_published = true);

create or replace function public.set_blog_posts_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_blog_posts_updated_at on public.blog_posts;
create trigger set_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_blog_posts_updated_at();

insert into public.blog_posts (title, slug, excerpt, content, cover_url, cover_alt, seo_title, seo_description)
values
('Comprar apartamentos en Ciudad de Guatemala: guía actualizada','comprar-apartamentos-ciudad-guatemala','Una guía práctica para comparar ubicación, precio, amenidades y opciones digitales antes de comprar.','El mercado de apartamentos en Ciudad de Guatemala ha crecido de forma importante durante los últimos años. Cada vez existen más proyectos residenciales con distintas ubicaciones, precios y amenidades.\n\nAntes de tomar una decisión conviene comparar la ubicación, el precio total, las características del proyecto y los servicios que ofrece. Zonas como la 10, 14 y 16 concentran una amplia variedad de opciones, aunque también existen nuevas áreas con propuestas atractivas.\n\nLas herramientas digitales permiten explorar proyectos, revisar sus características y comparar alternativas antes de programar una visita. Una búsqueda organizada ayuda a tomar una decisión con mayor claridad.','/blog/comprar-apartamentos-ciudad-guatemala.png','Vista de apartamentos modernos en Ciudad de Guatemala','Comprar apartamentos en Ciudad de Guatemala | Sitúa','Guía para comparar apartamentos, zonas, precios y amenidades en Ciudad de Guatemala.'),
('Apartamentos pequeños en Guatemala: tendencia en crecimiento','apartamentos-pequenos-guatemala','Por qué los apartamentos compactos y tipo estudio atraen a profesionales e inversionistas.','Los apartamentos pequeños y tipo estudio se han convertido en una alternativa frecuente en Guatemala. Su distribución eficiente responde a las necesidades de profesionales jóvenes, personas que desean vivir cerca de sus actividades e inversionistas que buscan propiedades fáciles de administrar.\n\nLos desarrollos actuales aprovechan mejor cada metro cuadrado mediante espacios integrados, almacenamiento funcional y amenidades compartidas. El resultado puede ser una vivienda moderna con costos de mantenimiento más controlados.\n\nAntes de elegir, es importante revisar la distribución real, la iluminación, el almacenamiento, la ubicación y la demanda de renta del sector.','/blog/apartamentos-pequenos-guatemala.png','Interior de un apartamento tipo estudio moderno','Apartamentos pequeños en Guatemala | Sitúa','Conoce la tendencia de apartamentos pequeños y tipo estudio en Guatemala.'),
('Inversión inmobiliaria en Guatemala: cómo empezar desde cero','inversion-inmobiliaria-guatemala','Principios básicos para definir una estrategia, comparar proyectos y evaluar el potencial de una inversión.','Empezar a invertir en bienes raíces requiere una estrategia clara. El primer paso es definir el objetivo: generar ingresos por renta, buscar plusvalía a mediano plazo o adquirir una propiedad para uso futuro.\n\nLuego conviene comparar propiedades terminadas y proyectos en preventa. La preventa puede ofrecer condiciones iniciales atractivas y potencial de valorización durante la construcción, mientras que una propiedad terminada permite evaluar y utilizar el inmueble de inmediato.\n\nLa ubicación, la demanda de renta, el respaldo del desarrollador, el presupuesto total y las condiciones de financiamiento deben analizarse en conjunto antes de tomar una decisión.','/blog/inversion-inmobiliaria-guatemala.png','Persona evaluando una inversión inmobiliaria','Inversión inmobiliaria en Guatemala: cómo empezar | Sitúa','Guía inicial para evaluar proyectos y comenzar una inversión inmobiliaria en Guatemala.'),
('Apartamentos en renta vs compra: qué conviene en Guatemala','apartamentos-renta-vs-compra-guatemala','Compara la flexibilidad de rentar con la construcción de patrimonio que ofrece comprar.','Rentar y comprar responden a necesidades distintas. La renta ofrece flexibilidad para cambiar de ubicación y requiere una inversión inicial menor. La compra, en cambio, puede ayudar a construir patrimonio y brindar mayor estabilidad.\n\nPara comparar ambas opciones es necesario considerar cuánto tiempo se planea permanecer en la propiedad, el enganche disponible, la cuota mensual, los gastos de mantenimiento y los costos asociados a la compra.\n\nNo existe una respuesta única. La mejor alternativa depende de la situación financiera, los planes personales y las opciones disponibles en la zona de interés.','/blog/renta-vs-compra-guatemala.png','Pareja comparando la renta y compra de un apartamento','Rentar o comprar apartamento en Guatemala | Sitúa','Compara las ventajas de rentar o comprar un apartamento en Guatemala.'),
('Cómo elegir el mejor proyecto inmobiliario en Guatemala','elegir-proyecto-inmobiliario-guatemala','Los factores esenciales para evaluar ubicación, desarrollador, calidad, amenidades y etapa del proyecto.','Elegir un proyecto inmobiliario implica revisar más que el diseño del apartamento. La ubicación, la experiencia del desarrollador, la calidad de construcción y la propuesta general del proyecto son factores esenciales.\n\nTambién conviene evaluar las amenidades, los accesos, los servicios cercanos, el mantenimiento esperado y la distribución de las unidades. Estos elementos influyen tanto en la experiencia de vivir como en el valor futuro de la propiedad.\n\nLos proyectos en preventa pueden ofrecer ventajas de precio y selección, pero requieren revisar cuidadosamente los plazos, contratos y antecedentes del desarrollador.','/blog/elegir-proyecto-inmobiliario-guatemala.png','Maqueta y materiales de un proyecto inmobiliario','Cómo elegir un proyecto inmobiliario en Guatemala | Sitúa','Aprende a comparar ubicación, calidad, amenidades y respaldo de proyectos inmobiliarios.'),
('Zonas emergentes para invertir en apartamentos en Guatemala','zonas-emergentes-apartamentos-guatemala','Cómo detectar sectores con nuevos desarrollos, precios competitivos y potencial de crecimiento.','Además de las zonas residenciales tradicionales, existen sectores que comienzan a atraer nuevos proyectos de apartamentos. Estas áreas pueden ofrecer precios de entrada más accesibles y oportunidades de crecimiento a mediano plazo.\n\nPara identificar una zona emergente conviene observar la construcción de vivienda, la mejora de accesos, la llegada de comercios y servicios, y la demanda de renta. Ningún indicador debe evaluarse de manera aislada.\n\nComparar proyectos y entender el desarrollo urbano del sector ayuda a distinguir una oportunidad real de una expectativa sin suficiente respaldo.','/blog/zonas-emergentes-guatemala.png','Zona residencial emergente con nuevos apartamentos','Zonas emergentes para invertir en Guatemala | Sitúa','Descubre qué revisar al evaluar zonas emergentes para invertir en apartamentos.'),
('Cómo funciona el financiamiento para apartamentos en Guatemala','financiamiento-apartamentos-guatemala','Aspectos que debes comparar entre enganche, tasa, plazo, cuota y gastos asociados.','El financiamiento permite distribuir el costo de un apartamento a lo largo del tiempo. Las condiciones pueden variar según la institución, el proyecto, el perfil del comprador y el monto del enganche.\n\nAntes de elegir es importante comparar la tasa de interés, el plazo, la cuota mensual, los seguros, las comisiones y cualquier gasto adicional. Una cuota aparentemente menor puede implicar un costo total más alto si el plazo es más largo.\n\nConsultar varias opciones y calcular el presupuesto completo permite entender qué propiedad es sostenible para las finanzas personales.','/blog/financiamiento-apartamentos-guatemala.png','Asesoría de financiamiento para comprar un apartamento','Financiamiento para apartamentos en Guatemala | Sitúa','Conoce cómo comparar tasas, plazos, enganche y cuotas para financiar un apartamento.'),
('Apartamentos de lujo en Guatemala: qué ofrecen','apartamentos-lujo-guatemala','Ubicación, diseño, privacidad y amenidades que distinguen a una propuesta residencial premium.','Los apartamentos de lujo suelen diferenciarse por su ubicación, arquitectura, acabados, privacidad y nivel de servicio. Sectores como las zonas 14 y 15 concentran varias propuestas de este segmento.\n\nEntre sus características pueden encontrarse vistas amplias, áreas sociales, seguridad, espacios de bienestar y materiales de mayor especificación. Sin embargo, cada proyecto combina estos elementos de manera distinta.\n\nAdemás del precio de compra, conviene revisar las cuotas de mantenimiento, la calidad de administración y la demanda del sector para valorar su potencial de conservación y crecimiento.','/blog/apartamentos-lujo-guatemala.png','Sala de un apartamento de lujo con vista a la ciudad','Apartamentos de lujo en Guatemala | Sitúa','Conoce las características, amenidades y ubicaciones de apartamentos de lujo en Guatemala.'),
('Cómo generar ingresos con apartamentos en renta en Guatemala','generar-ingresos-apartamentos-renta-guatemala','Factores que influyen en la ocupación, el ingreso mensual y el rendimiento de un apartamento para renta.','Un apartamento puede generar ingresos periódicos cuando existe demanda de renta y la propiedad se administra de manera adecuada. La ubicación, el tamaño, el estado del inmueble y los servicios cercanos influyen en su capacidad de atraer inquilinos.\n\nAntes de invertir conviene estimar el ingreso mensual y descontar mantenimiento, seguros, impuestos, periodos sin ocupación y reparaciones. Esta proyección permite analizar el rendimiento de forma más realista.\n\nLos proyectos en preventa y construcción también pueden ser una alternativa, siempre que los plazos y el crecimiento esperado del mercado sean compatibles con la estrategia del inversionista.','/blog/ingresos-apartamentos-renta-guatemala.png','Apartamento preparado para generar ingresos por renta','Ingresos con apartamentos en renta en Guatemala | Sitúa','Aprende qué revisar para generar ingresos con un apartamento en renta en Guatemala.'),
('Qué revisar antes de comprar un apartamento en Guatemala','que-revisar-antes-comprar-apartamento-guatemala','Una lista esencial para evaluar el inmueble, el proyecto, los documentos y el financiamiento.','Antes de comprar un apartamento es importante revisar el precio total, la ubicación y la calidad general del proyecto. También deben considerarse la distribución, la iluminación, los acabados y el funcionamiento de puertas, ventanas e instalaciones.\n\nEn el aspecto documental conviene verificar el contrato, los plazos, las condiciones de entrega, el régimen de propiedad y las obligaciones de mantenimiento. Si se utilizará financiamiento, la cuota debe analizarse junto con seguros y gastos asociados.\n\nExplorar y comparar alternativas en línea antes de visitar ayuda a concentrar el tiempo en las propiedades que realmente se ajustan a las necesidades y al presupuesto.','/blog/revisar-antes-comprar-apartamento.png','Inspección de un apartamento antes de comprarlo','Qué revisar antes de comprar un apartamento | Sitúa','Lista de aspectos físicos, financieros y documentales para revisar antes de comprar.'),
('Ventajas de comprar apartamentos en preventa en Guatemala','ventajas-apartamentos-preventa-guatemala','Precio inicial, selección de unidades y potencial de valorización durante la construcción.','Comprar en preventa significa adquirir una unidad antes de que el proyecto esté terminado. Esta etapa puede ofrecer precios iniciales más favorables, planes de pago para completar el enganche y una mayor selección de ubicaciones dentro del edificio.\n\nTambién existe la posibilidad de valorización durante la construcción. No obstante, el comprador debe evaluar el historial del desarrollador, los permisos, el contrato, el calendario y las condiciones de entrega.\n\nLa preventa puede ser útil para vivienda o inversión cuando sus plazos, riesgos y condiciones se alinean con los objetivos del comprador.','/blog/apartamentos-preventa-guatemala.png','Maqueta de apartamentos en preventa junto a una obra','Ventajas de comprar apartamentos en preventa | Sitúa','Conoce beneficios y aspectos a revisar al comprar apartamentos en preventa en Guatemala.'),
('Sitúa.gt: la forma más fácil de encontrar apartamentos en Guatemala','situa-encontrar-apartamentos-guatemala','Explora proyectos, compara opciones y encuentra información organizada para decidir con mayor claridad.','Buscar apartamento puede implicar visitar múltiples sitios y ordenar información presentada de maneras distintas. Sitúa.gt reúne proyectos inmobiliarios en un solo lugar para facilitar la exploración y comparación.\n\nLa plataforma permite conocer ubicaciones, modelos, características y rangos de precio disponibles. Así, cada persona puede filtrar opciones y entender mejor la oferta antes de contactar o visitar un proyecto.\n\nNuestro objetivo es hacer que encontrar vivienda nueva en Guatemala sea un proceso más claro, ordenado y útil para compradores e inversionistas.','/blog/situa-encontrar-apartamentos-guatemala.png','Persona explorando apartamentos disponibles en Sitúa','Encontrar apartamentos en Guatemala con Sitúa.gt','Explora y compara proyectos de apartamentos en Guatemala de forma clara con Sitúa.gt.')
on conflict (slug) do nothing;
